stages:
  - format
  - build
  - tests
  - deploy
  - notification

format_project:
  stage: format
  script:
    - chmod +x ./format.sh
    - ./format.sh

build_project:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq make gcc
  script:
    - cd src && make
  artifacts:
    paths:
      - src/build/       
    expire_in: 30 days

tests_project:
  stage: tests
  script:
    - chmod +x src/tests/tests.sh
    - cd src/tests && ./tests.sh
  when: on_success 
  allow_failure: false
  after_script:
    - if [ "$CI_JOB_STATUS" != "SUCCESS!!!" ]; then echo "FAIL!"; fi

deploy_project:
  stage: deploy
  before_script:
  script:
    - ls -la ~/.ssh
    - chmod +x deploy.sh
    - ./deploy.sh
  when: manual
  allow_failure: false
  after_script:
    - ./bot.sh "$CI_JOB_STATUS"

notifications_project:
  stage: notification
  before_script:
  script:
    - chmod +x bot.sh
    - ./bot.sh
  allow_failure: false
  