stages:
  - format
  - build
  - tests
  - deploy

format_project:
  stage: format
  script:
#!/bin/bash

if [ ! -f src/.clang-format ]; then
    cp materials/linters/.clang-format src/
  else
    exit 2
  fi

FORMAT_DIFF=$(find src/ -name "*.c" -o -name "*.h" \
  | xargs clang-format -style=file -output-replacements-xml \
  | grep -c "<replacement ")

if [ "$FORMAT_DIFF" -ne 0 ]; then
  find src/ -name "*.c" -o -name "*.h" | while read file; do
    echo "▶ $file"
    diff -u "$file" <(clang-format -style=file "$file")
  done
  exit 1
else
  echo "SUCCESS!"
fi

build_project:
  stage: build
  script:
    - cd src
    - make
  artifacts:
    name: "build-artifacts"
    paths:
      - src/build/       
    expire_in: 30 days

tests_project:
  stage: tests
  script:
    - chmod +x tests/tests.sh
    - ./src/tests/tests.sh
  when: on_success 
  allow_failure: false
  after_script:
    - |
      if [ "$CI_JOB_STATUS" = "success" ]; then
        echo "TEST: SUCCES!"
      else
        echo "TEST: FAIL!"
      fi

deploy_project:
  stage: deploy
  script:
    - chmod +x deploy.sh
    - ./deploy.sh
  when: manual
  allow_failure: false
  dependencies:
    - build_project      
  artifacts:
    paths:
      - src/build/