stages:
  - format
  - build
  - tests
  - deploy
  - notification

format_project:
  stage: format
  before_script:
    - apt-get update -qq && apt-get install -y -qq install clang-format
  script:
    - chmod +x ./format.sh
    - ./format.sh
  allow_failure: false

build_project:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq make gcc
  script:
    - cd src && make
  artifacts:
    paths:
      - src/build/       
    expire_in: 30 days
  allow_failure: false

tests_project:
  stage: tests
  script:
    - chmod +x src/tests/tests.sh
    - cd src/tests && ./tests.sh
  when: on_success 
  allow_failure: false
  after_script:
    - if [ "$CI_JOB_STATUS" != "SUCCES!" ]; then echo "FAIL!"; fi
  

deploy_project:
  stage: deploy
  before_script:
  script:
    - ls -la ~/.ssh
    - chmod +x deploy.sh
    - ./deploy.sh
  when: manual
  allow_failure: false
  after_script: 
    - chmod +w /home/gitlab-runner/env.sh
    - echo "DEPLOY_JOB_STATUS=$CI_JOB_STATUS" >> /home/gitlab-runner/env.sh

notifications_project:
  stage: notification
  script:
    - chmod +x bot.sh
    - ./bot.sh
  